//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Client_Loyalty.Models.lifsEF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Movimientos
    {
        public int MovimientoID { get; set; }
        public int Usuario { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Descripcion { get; set; }
        public decimal Monto { get; set; }
        public int CuentaID { get; set; }
    
        public virtual Cuentas Cuentas { get; set; }
        public virtual Usuarios Usuarios { get; set; }
    }
}
